### ISSUE TITLE
CI tracking issue

### ISSUE THREAD

**Issue by jurraca** [asmap/kartograf#34]
We should get some CI going. I think the TODO looks something like the below. Would love some input as I haven't done a ton of CI setup before.

- [ ] Initial configuration: builds the Nix flake and outputs #33 
- [ ] After tests are added, run tests as well 
- [ ] self-host Github runner ? maybe with [this](https://github.com/bitcoin-dev-tools/nix-github-runner/tree/master)

**Comment by fjahr** [comment]
Sounds good. I was thinking of having a linter job would be lowest hanging fruit for the start. just pylint and/or flake8, the only real work is figuring out what errors we want to ignore and then fix the rest. I had started that process a few weeks ago and I will open a PR for that asap. I guess I can tag it on to the initial config PR.

**Comment by jurraca** [comment]
i've been using `ruff` but I don't have any opinion on the best tool. Are you doing one big linting / formatting pass on the project? figure that's best as its own PR, yea.

**Comment by fjahr** [comment]
I've never used `ruff`, we've been using `pylint` and `flake8` in core so that's what I am used to.

I've opened #35 as a start, fixing some of the more interesting errors and marking a few others as ignored for now. We can fix these as we go along but most importantly this should be good to detect some stuff like unused variables and actual errors in code path we might have forgotten to test.

**Comment by jurraca** [comment]
closing. current CI covers the bases imo. the self-hosted github runner is a nice-to-have and can be handled in a separate issue if needed.
